### ISSUE TITLE
Feature Request/Improvement Only one page for the report

### ISSUE THREAD

**Issue by 0xtavian** [FortyNorthSecurity/EyeWitness#358]
Its a real pain in the butt having to click through 175 pages (for example) and being limited to 20 results per-page. I like the way Gowitness does this by just displaying all results on one page. Its a lot easier to analyze. I usually scan at the very least 1k web services at a time, so you'd think the page feature was "designed" for people who do this type of scanning, but unfortunately its just cumbersome to navigate. Plus, parsing results is much more difficult when you have to do it across each page.

**Comment by ChrisTruncer** [comment]
Have you tried using the —results option which has been built into EyeWitness? You can specify the number of results that you want on each page.

This was introduced because when testing extremely large numbers of sites, if they were all loaded on one page, it would crash the web browser (or take forever to load).

**Comment by 0xtavian** [comment]
No i havent! That sounds exactly like what i need. I apologize for opening an issue for something that was already available. Please feel free to close/delete this.Thank you for your prompt response.
