### ISSUE TITLE
Error in the EyeWitness

### ISSUE THREAD

**Issue by robdollard** [FortyNorthSecurity/EyeWitness#368]
At startup, an error occurs.
![48696455-ce008e00-ec03-11e8-95db-0aee38966267](https://user-images.githubusercontent.com/40629638/48703861-e201bb00-ec16-11e8-9e8e-96d34242bcbd.png)

**Comment by ChrisTruncer** [comment]
The --web option would always work for you. --Web actually calls firefox headlessly in the background. I just merged in #369 into EyeWitness. This now removes the --headless option. This is because --web uses firefox headlessly so there is no need for --headless. You will want to do a git pull to grab the latest version of EyeWitness and then you should be good.
