### ISSUE TITLE
Getting TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by creativetoken** [FortyNorthSecurity/EyeWitness#388]
## OS Used - ALL Information (architecture, linux flavor, etc.)
X64, Kali Linux

## Pastebin link to error you are encountering
https://pastebin.com/aGxujzt5

## Expected behavior (vs. what you encountered)
I am getting the error on running Eyewitness against a list of subdomains. It takes scrrenshot for sometime and abruptly stops with the below error.

Traceback (most recent call last):
  File "./EyeWitness.py", line 609, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 539, in multi_mode
    sort_data_and_write(cli_parsed, results)
  File "/root/EyeWitness/modules/reporting.py", line 199, in sort_data_and_write
    csv_request_data += url.hostname + ","
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
root@kali:~/EyeWitness#

## Any additional information

Attached subdomain list file
[subsony.txt](https://github.com/FortyNorthSecurity/EyeWitness/files/2850256/subsony.txt)

**Comment by ChrisTruncer** [comment]
Thanks for providing all the information I needed to look into this. I'll check it out

**Comment by ChrisTruncer** [comment]
I reviewed the list of URLs you are providing, and it's because it's in a format that EyeWitness isn't expecting. I can add in something to the error handling to make sure to state that (will get it merged in shortly).

But your second URL doesn't look for be an actual URL. Also, other domains are starting with a ".". To make up an example, ".fortynorthsecurity.com". EyeWitness would want the domain to not start with a ".", or to have a subdomain.

**Comment by ChrisTruncer** [comment]
I'm also double checking to make sure this is right

**Comment by creativetoken** [comment]
Many Thanks Chris. This tool is super awesome :)

**Comment by ChrisTruncer** [comment]
So I confirmed that that is indeed the issue. The specific record it that is causing the issue has "?" as the subdomain, and is causing the problem. With a list of properly formatted URLs, it should all work.

I just pushed in a fix which will now throw an error stating it's a bad URL rather than just throwing the error message you saw.

Thanks for submitting this!
