### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by HanseSecure** [FortyNorthSecurity/EyeWitness#389]
### Steps to reproduce

<code>apt-get install eyewitness </code><br>
<code>eyewitness  --single http://www.gmail.com --all-protocols </code><br>

or clone and setup.sh from this repo <br>
<code>python EyeWitness.py --single http://www.gmail.com --all-protocols</code><br>

### Expected behaviour
screenhots && report ;-)

### Error Message
<code>
Attempting to screenshot http://www.gmail.com </code><br>
<code>Message: Unable to find a matching set of capabilities
</code>

### Environment
**Operating system**:
Recent Kali Rolling (2019.1)

### Additional Info
I already checked the issues #376  && #356 <br>
#376 
setup.sh included your firefox fix ;-)
#356 
The command in the solution of #356 <br><code>eyewitness --single http://www.gmail.com --timeout 10 --headless</code><br> doenst worked for me :-( 
<br>
Another question is the <code>--headless</code> option still present?
<br>
Thanks in Advance

**Comment by ChrisTruncer** [comment]
Hi there, to go through all your questions

Can you try installing on a fresh Kali VM? I just downloaded the latest ISO (20 minutes ago), and installed EyeWitness on there. After installing it, it worked out of the box without an issue. With that said, I would also recommend to **not** install via apt. I would suggest cloning this repo and then running the setup script. That's what I was able to do and everything worked. (Side note, you can call EyeWitness.py by using ./EyeWitness.py, you shouldn't need to call python in front of it).

Also, --headless is not present anymore. The reason for this is because selenium is already calling FireFox/IceWeasel headlessly, so the --headless option was removed since it is already happening in --web.

Thanks!

**Comment by HanseSecure** [comment]
Hey Chris,

I will try this and report it next week. 

PS. Just added the python above to show the difference to apt-get call xD

Cheers
Flo

**Comment by ChrisTruncer** [comment]
Ha, fair enough. Thank you!

**Comment by ChrisTruncer** [comment]
Hey, just wanted to check in and see if you were able to get everything working on your end

**Comment by HanseSecure** [comment]
Hey Chris,
with a fresh kali-light and your github setup it is working. Only the <code>python-bs4</code> packet is missing on that kali version. After apt-get install it works like a charm.

Unfortunately i have no idea how to fix it on my other kali installation :-(

But thats my problem ;-)

**Comment by tit0n** [comment]
Make sure you don't run EyeWitness.py as root. 
Running Firefox as root in a regular user's session is not supported.

**Comment by Bibek1Shah** [comment]
["><svg/onload onerror=alert(1)>](url)

**Comment by srajaram93** [comment]
> Make sure you don't run EyeWitness.py as root.
> Running Firefox as root in a regular user's session is not supported.

This worked for me! Thank you!

**Comment by x13x13x** [comment]
Hey guys I did find a solution for the problem here. Had the same issue with an updated Kali VM on Vmware Fusion. 

Problem was as you already mentioned here: 

1. Firefox is not allowed be run as root in a normal user session --> This creates the Error "Unable to find a matching set of capabilities"
2. Now I tried to run it without Sudo --> Permission denied with some kind of jQuery library --> So this does not work either
3. Tried to run it as Sudo -su "root-session" but it seems that it also only a root privilege in a normal users session
4. Final solution how it did work out --> Created a root account on kali and did run it logged in as root 
===> Worked like a charm.

So maybe use this work around until the  permission problems get fixed and @ChrisTruncer and @HanseSecure maybe you can find some kind of solution for this problem? I dont know if I am the only one stumbling on this issue but it seems it is not a problem on my systems side and I think before Kali changed their policies to non root users it worked out fine.
Thanks for creating such an awesome tool as Eyewitness anyway. Just want to help out here :) Keep it up!

**Comment by Kosmonit** [comment]
> Hey guys I did find a solution for the problem here. Had the same issue with an updated Kali VM on Vmware Fusion.
> 
> Problem was as you already mentioned here:
> 
>     1. Firefox is not allowed be run as root in a normal user session --> This creates the Error "Unable to find a matching set of capabilities"
> 
>     2. Now I tried to run it without Sudo --> Permission denied for some kind of jQuery library --> So this does not work either
> 
>     3. Tried to run it as Sudo -su "root-session" but it seems that it also only a root privilege in a normal users session
> 
>     4. Final solution how it did work out --> Created a root account on kali and did run it logged in as root
>        ===> Worked like a charm.
> 
> 
> So maybe use this work around until the permission problems get fixed and @ChrisTruncer and @HanseSecure maybe you can find some kind of solution for this problem? I dont know if I am the only one stumbling on this issue but it seems it is not a problem on my systems side and I think before Kali changed their policies to non root users it worked out fine. Thanks for creating such an awesome tool as Eyewitness anyway. Just want to help out here :) Keep it up!

Thanks!
