### ISSUE TITLE
Can not connect to the Service geckodriver

### ISSUE THREAD

**Issue by exrme18** [FortyNorthSecurity/EyeWitness#391]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Linux 4.9.0-8-amd64 (Debian)

## Pastebin link to error you are encountering
<img width="467" alt="screenshot 2019-03-08 at 4 55 44 pm" src="https://user-images.githubusercontent.com/40659223/54026211-1e0b5c80-41c3-11e9-8da6-525dfcd715c1.png">

## Expected behavior (vs. what you encountered)
It should generate the result in the folder with screenshots. 

## Any additional information

Running on Linode server

**Comment by ChrisTruncer** [comment]
I've tested this on a clean debian install I personally made on a VM, and tested on DigitalOcean and Linode (brand new debian instance) and EyeWitness works perfectly on all of them. So it was likely an issue with your installation, or not running the setup script. Please try it again, because I verified that it does work on Linode.

**Comment by sirchsec** [comment]
I got this same error while attempting to use the tool through proxychains. Removing proxychains it started working normally.
