### ISSUE TITLE
Error when attempting --rdp 

### ISSUE THREAD

**Issue by rumhamstuff** [FortyNorthSecurity/EyeWitness#422]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

## Pastebin link to error you are encountering
https://pastebin.com/d3Tx4SY2

> Traceback (most recent call last):
  File "./EyeWitness.py", line 611, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 420, in multi_mode
    url_list, rdp_list, vnc_list = target_creator(cli_parsed)
  File "/opt/EyeWitness/modules/helpers.py", line 519, in target_creator
    parser.parse(command_line_object.x)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)

## Expected behavior (vs. what you encountered)
Would like to be able to get screenshots from RDP.

## Any additional information

Everything else seems to be working just fine, but --rdp does not.

**Comment by ChrisTruncer** [comment]
This looks to be an issue with the XML file that you are providing EyeWitness. It might be easier to use a flat text file with the IPs/Hostnames to target.

With that said, at this point RDP isn't being supported since it is not (currently in EyeWitness version 3). Once it gets added in when a library supports it, then we'll be able to support it again. Big the likely fix will be to get properly formatted XML or just make your own text file containing the systems to target.
