### ISSUE TITLE
Removal of os.system('clear')

### ISSUE THREAD

**Issue by n00py** [FortyNorthSecurity/EyeWitness#456]
Just a feature request.  When ever EyeWitness runs, it clears the screen.  I know at least on Kali, "clear" even clears the scrollback.  This has tripped me up several times where I had something important in the terminal window above and then it gets wiped out.  It seems clearing it has a minor aesthetic enhancement, but I know at least I greatly prefer to retain the previous terminal output.  

```
def title_screen():
    """Prints the title screen for EyeWitness
    """
    if platform.system() == "Windows":
        os.system('cls')
    else:
        os.system('clear')
```

**Comment by n00py** [comment]
proposed fix: #559

**Comment by ChrisTruncer** [comment]
@pmsosa - I have to admit, your response is incredibly off-putting and disrespectful. This is a project myself, and others, have spent their own personal time on building when we obviously could have been doing anything else. I'm happy to make this project public and share it for anyone to use, but it's really uncalled for to have you come in and essentially trash it and say how in your opinion horrible decisions were made. For someone using someone else's work/volunteer time, it comes across very entitled and quite honestly makes me not want to help you in any way.

The clear was put in there because **I** find it useful, myself, the primary author of the tool. This script was written for myself, not for the community as a whole. Now it obviously was made public in the event that it is helpful for anyone else, but it was written for my use on tests, not yours. If you're that upset by how it was built, fork it and use your own fork with your own customizations, or just write your own tool. I think it's fair to ask that next time you comment on this, or someone else's work that they made free, that you do so in a respectful manner.

**Comment by pmsosa** [comment]
@ChrisTruncer, you are right. 
I do sincerely apologize, at the time I was frustrated due to my own reasons and I shouldn't have taken out on the team working on this tool. I hope you are not discouraged by my rudeness on this occasion; I do appreciate the time you and others have put on the tool. Again, apologies for the rude comment and hope you have a good rest of the week.

**Comment by Relkci** [comment]
#647
