### ISSUE TITLE
Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by zoben10** [FortyNorthSecurity/EyeWitness#462]
I use the latest Kali Linux version. I just install EyeWitness. When I run the command : 
$ `sudo ./EyeWitness.py --web -f /home/Hello/Documents/URLS.txt`

![image](https://user-images.githubusercontent.com/61861342/76686880-5ecb5c00-65f5-11ea-9db6-ee50d17a49c4.png)

![image](https://user-images.githubusercontent.com/61861342/76686895-94704500-65f5-11ea-907d-3dcd8ff8aed2.png)

Please help. Thank you !

**Comment by petkyrk** [comment]
Same issue on my end. Clean installation of latest Kali VM (tried the same with Ubuntu). Same exact message. I tried multiple VMs

**Comment by AnotherWayIn** [comment]
Same here on the latest kali docker image

**Comment by sctf2020** [comment]
from #458 : In the latest versions of Kali, you cannot run EyeWitness as root (with sudo) otherwise you'll get a very vague error message of "Message: Unable to find a matching set of capabilities". If you read "geckodriver.log", you'll see the real error message of "Running Firefox as root in a regular user's session is not supported."

**Comment by ChrisTruncer** [comment]
Did the above fix this? Don't run as root/sudo? Will close because I think this should fix it, but want to see if anyone else has issues

**Comment by sctf2020** [comment]
It does in fact fix the issue.


Alexander Storm
OSCP, GXPN, CASP
Project Lead / Lead Designer
StormCTF

w: stormctf.ninja  e: alex@stormctf.ninja
<https://twitter.com/offsec_ginger>

**Comment by ChrisTruncer** [comment]
Thanks, closing this out
