### ISSUE TITLE
Failed to decode response from marionette

### ISSUE THREAD

**Issue by Nikhil15292** [FortyNorthSecurity/EyeWitness#465]
I am using command:  ./EyeWitness.py -f temp.txt --web 

environment: windows subsystem for Linux (Ubantu terminal) 

Getting error :
Starting Web Requests (869 Hosts)
Message: Failed to decode response from marionette

**Comment by Nikhil15292** [comment]
Getting output:
Finished in 51.70343065261841 seconds
[*] No report files found to open, perhaps no hosts were successful

**Comment by digininja** [comment]
Are you running it on a box with limited memory? A quick google says that
error often happens when the system runs out of memory.

**Comment by Nikhil15292** [comment]
in the box 64 gb is available

**Comment by Nikhil15292** [comment]
i tried to do it for google. and i am receiving same response 
Attempting to screenshot https://google.com
Message: Failed to decode response from marionette

**Comment by digininja** [comment]
That is the box, but is it running in a VM or docker or anything like that?

**Comment by Nikhil15292** [comment]
This is running in windows only. i am using windows subsystem for linux.  Ubantu terminal in windows

**Comment by digininja** [comment]
I'll pass it over to Chris then as I'm out of ideas.

**Comment by Nikhil15292** [comment]
Ok...Thnaks digininja/...i am waiting for Chris reply

**Comment by digininja** [comment]
You could try the new windows release while you are waiting.

**Comment by Nikhil15292** [comment]
i tried windows precompiled version. but this tool doesn't support powershell

**Comment by ChrisTruncer** [comment]
The Windows version isn't PowerShell. It's a .Net application you can just download and run. All you need to do is provide it a path to a file containing the urls. You can also use PowerShell to run it, but it is not a PowerShell script.

On the original note, as of now, I've not tested WSL so I don't know what sort of dependency issues might exist on it. I have updated the setup script to use the latest version of the geckodriver (which uses the marionette protocol). Feel free to try. Otherwise my recommendation would be to test it out on a supported system (not in WSL) and it should work there (or please provide a repeatable issue so we can recreate and debug it on our end).

**Comment by Nikhil15292** [comment]
Yes, I am also trying to solve  geckodriver issue. BTW i downloaded windows version of Eyewitness. Can you provide me list of commands which i can use to run Eyewitness on powershell.

**Comment by ChrisTruncer** [comment]
Please look at the readme, and again, this is not a PowerShell script.

**Comment by Nikhil15292** [comment]
On windows which terminal do you suggest to use for eyewitness ? i was using powershell and it is throwing error like 
[*] ERROR: Web page possibly blank or SSL error!
