### ISSUE TITLE
the windows client can't fire up

### ISSUE THREAD

**Issue by xxnbyy** [FortyNorthSecurity/EyeWitness#471]
When i download the eyewitness.exe and start to run it first time.

[+] Firing up EyeWitness...
[*]ERROR: Could not obtain categories and signatures from Github!
[*]ERROR: Try again, or see if Github is blocked?

but i the github is not be blocked ,and i can visit it now.

**Comment by xxnbyy** [comment]
Then i use admin console to run it ,it solved

**Comment by h4cnull** [comment]
categories and signatures file url:
    https://raw.githubusercontent.com/FortyNorthSecurity/EyeWitness/master/Python/categories.txt
    https://raw.githubusercontent.com/FortyNorthSecurity/EyeWitness/master/Python/signatures.txt

change dns server : 8.8.8.8  8.8.4.4

**Comment by alandixon** [comment]
Hmmm. The DNS fix didn't work for me so I fired up Visual Studio.
An exception is thrown in `DictMaker()` at
`catCode = witnessClient.DownloadString(catURL);`
The exception is
_The request was aborted: Could not create SSL/TLS secure channel._
and the fix is to add these two lines
```
ServicePointManager.Expect100Continue = true;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```
just before `witnessClient` is initialised at
`WebClient witnessClient = new WebClient();`
This forces TLS v1.2 which seems to do the trick.

I'm happy to push the change up as a branch to be merged ... let me know
Regards
Alan

**Comment by ChrisTruncer** [comment]
If you are able to, we'd definitely appreciate a quick PR with the fix. It would also help to make sure you get the credit for it.

**Comment by alandixon** [comment]
Not done one of these before, but I think I've done my bit:  [https://github.com/FortyNorthSecurity/EyeWitness/pull/521](https://github.com/FortyNorthSecurity/EyeWitness/pull/521)
Let me know if I've missed something!
