### ISSUE TITLE
Error While Running The Program!

### ISSUE THREAD

**Issue by Xeek3y** [FortyNorthSecurity/EyeWitness#497]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Linux 2019x64

## Pastebin link to error you are encountering
https://pastebin.com/kSSrFaKZ

## Expected behavior (vs. what you encountered)
The program is not running for me, idk wth is wrong but i installed all the requirements but still i don't get it why it's not working :/

## Any additional information
Command:
`python3 ./EyeWitness.py -f domains.txt`

**Comment by ChrisTruncer** [comment]
It doesn't look like you ran the setup script, because you're missing a dependency (xvfb). Also, you aren't running it correctly, you need to also specify the --web flag. It might be worth checking out the readme on how to run the script.

If this doesn't help, please feel free to respond to the issue and let me know what all you have tested and done.

**Comment by Xeek3y** [comment]
> 
> 
> It doesn't look like you ran the setup script, because you're missing a dependency (xvfb). Also, you aren't running it correctly, you need to also specify the --web flag. It might be worth checking out the readme on how to run the script.
> 
> If this doesn't help, please feel free to respond to the issue and let me know what all you have tested and done.

I ran the `setup.sh` script what is in setup folder with sudo permission and i tried to repeat the same process again with `--web` flag but i'm still getting errors!
