### ISSUE TITLE
(with proposed fix!) Issue with incomplete scan results in blocking error creating index page

### ISSUE THREAD

**Issue by pmularien** [FortyNorthSecurity/EyeWitness#520]
We encountered an issue running EW where a scan could not be completed due to hanging accessing certain sites. We were able to bypass this error by manually editing the `http` table in the sqlite database and setting the offending sites' `complete` column value to `1` - this allowed the scan to complete, but we encountered the blocking error below when EW was generating the final report.

## OS Used - ALL Information (architecture, linux flavor, etc.)
WSL2

## Pastebin link to error you are encountering
https://pastebin.com/0UHk08Pv

## Expected behavior (vs. what you encountered)
I would expect EW to skip the site in error and continue on

## Any additional information
We have a proposed fix which I can confirm allowed the generation of the site to complete. Simply add an `except AttributeError` in `eyewitness/modules/objects.py`:

```python
            try:
                html += "\n<br><b> Page Title: </b>{0}\n".format(
                    self.sanitize(self.page_title))
            except AttributeError:
                html += "\n<br><b> Page Title:</b>{0}\n".format(
                    'Unable to Display')
            except UnicodeEncodeError:
                html += u"\n<br><b> Page Title:</b>{0}\n".format(
                    self.sanitize(self.page_title))
```

Could you please incorporate this into the codebase (or I can create a trivial PR, up to you)? Thanks!

**Comment by ChrisTruncer** [comment]
Hey, sorry for the late review. I'd certainly be happy with a pull request on this (and it will give you the credit in the code base). Would you be able to submit it?

**Comment by 0x6d6f7468** [comment]
Hey @ChrisTruncer, big fan of the tool and looking to contribute. This issue has bitten me a few times at this point and I would love to help try and figure it out.

Adding the `AttributeError` exception and manually setting the hosts to be complete in the sqlite database file is a decent workaround but I would imagine there's something else that could be done to prevent the issue from happening at all.

I can whip up a PR within the next few days if you're interested. Otherwise, I also plan to look into the code a bit further when I have time to see if I can't spot what might be causing the issue.
