### ISSUE TITLE
Message: Process unexpectedly closed with status 1

### ISSUE THREAD

**Issue by vansh1** [FortyNorthSecurity/EyeWitness#546]

**Comment by vansh1** [comment]
i am unable to use eyewitness
this is what i am getting after running eyewiness : 
Attempting to screenshot http://google.com
Message: Process unexpectedly closed with status 1

command i used is python3 EyeWitness.py --web --single google.com

i am using kali release Release: 2021.3

**Comment by vansh1** [comment]
can anyone gave solution why are you closing my issue

**Comment by ChrisTruncer** [comment]
When you opened the issue, you didn't provide any of the issue that was requested to help troubleshoot it. WIthout that information, it's hard to troubleshoot (which is why we ask for it and pre-populatate those prompts for you to answer them). So if issues are opened without them, then they are closed.

Additionally, I also tested out installing EyeWitness on a clean download of Kali, brand new install, and it worked without any issues. I would suggest looking at your VM and/or try testing on a clean VM because I don't know what customizations you made.

**Comment by vansh1** [comment]
I just clone the git repo run the setup.sh and now running the command i mentioned above and getting this issue

**Comment by digininja** [comment]
I've installed EW on four different boxes over the last two weeks, three of them Kali, no problems with any of them, all worked fine.

**Comment by vansh1** [comment]
what can be the problem then

**Comment by digininja** [comment]
Create a new Kali VM and try it in there, if that works, you've broken the
VM you are trying to install it in.

**Comment by djallalzoldik** [comment]
Try to make:
$sudo chmod 777 ~/EyeWitness/Python

**Comment by Olusmith8** [comment]
this issue still persists I'm currently having the same issue this is the command I used
./EyeWitness.py -x /home/kali/Desktop/sim.xml --web

the sim.xml file was output from Nmap scan

**Comment by ChrisTruncer** [comment]
Can you either upload your XML, or test it out and see if there's something malformed?

Did you resume the nmap scan?

**Comment by Olusmith8** [comment]
i did not resume the Nmap scan, i start the scan afresh below is my XML file, i change the extension to txt because of upload 
[sim.txt](https://github.com/FortyNorthSecurity/EyeWitness/files/9026594/sim.txt)

**Comment by Steiner-254** [comment]
~ An interesting error it is "Message: Process unexpectedly closed with status 1
"

**Comment by surendra780** [comment]
Message: Process unexpectedly closed with status 1
![Screenshot 2023-01-25 113935](https://user-images.githubusercontent.com/100469624/214493190-7565c1f9-b741-4b49-935d-b199c8cbad96.png)

i am facing this type of error please anyone help me

**Comment by justcacheme** [comment]
me too!

**Comment by k33psilence** [comment]
Try run _eyewitness_ via non root user. It worked for me.

**Comment by h4cks1lv3r** [comment]
Hello. I recently encountered this problem as well and realized it was because it was installed by a root user with "sudo" and therefore must have somehow changed the way it interacts with the individual files and directories within EyeWitness.

What worked for me is what an above user stated "chmod 777" to the eyewitness folder in /usr/share (that's where it installed for me on kali linux). I had to change everything inside that directory to 777 in order for it to work. It also would not work using the sudo command to run it prior to me doing this. After changing permissions, I'm able to use it normally now.

Hope this helps.

**Comment by maruf-cyb** [comment]
I have also face the same problem. 

but as suggested by @alexste46 running it via non-root user solved my problem

**Comment by henriquejunqueira** [comment]
I had installed it as root, but I changed the owner of the files in the entire "EyeWitness" and "EyeWitness/Python" folder to the common user using the command "chown myuser:mygroup *" and it worked normally. Initially I also got the error "Message: Process unexpectedly closed with status 1" as well. And checking the tips here and the installation logs I saw that it presented a Warning saying that using it as root could break the program or present problems, something like that.

**Comment by Garte153sa** [comment]
Same here
![Uploading Screenshot (63).png…]()

**Comment by Garte153sa** [comment]
Same here
![Uploading Screenshot (63).png…]()

**Comment by Parveen-Birthaliya** [comment]
Just restart the VM , and again run the eyewitness command it will get resolved

**Comment by bbh1010** [comment]
You only need to run this command 
chmod 777 geckodriver.log 
After run this command u able to run eyewitness as non root user

**Comment by Ankit-Kumar315** [comment]
i did everything written in above but still i am facing same issue => process unexpectedly closed with status 1 
what should i do please help me

**Comment by digininja** [comment]
Create a new issue, give us full information your environment and provide all the information requested in the template.

**Comment by Ankit-Kumar315** [comment]
![image](https://github.com/RedSiege/EyeWitness/assets/174734989/42741eed-a54f-4a5d-be8a-8c6f95427308)
then it will provide this
![image](https://github.com/RedSiege/EyeWitness/assets/174734989/d68c76c0-b935-46ec-9039-ceada22a5d74)

**Comment by Ankit-Kumar315** [comment]
what is wrong in this

**Comment by digininja** [comment]
What is the full, including protocol, URL of the site you are trying to
access?

**Comment by Ankit-Kumar315** [comment]
everything is right in this command of eyewitness

**Comment by Ankit-Kumar315** [comment]
what should i do
i tried everything in last week

**Comment by digininja** [comment]
Same question again, what is the full URL, including protocol, of the site
you are trying to access?
