### ISSUE TITLE
Intermittent crash taking screenshot

### ISSUE THREAD

**Issue by digininja** [FortyNorthSecurity/EyeWitness#575]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Latest Kali

## Pastebin link to error you are encountering

I've just ran a scan against about 600 IPs and got a bunch of these close to the end of the scan.

I tried to reproduce it by doing single screenshots and the results are 50/50, sometime the screenshot works OK, sometimes I get this error. Curl gets the page every time, no network latency issues or timeouts, the page that is causing this error is only 258 bytes, 555 with headers, no not a massive thing that would stall during loading.

```
Attempting to screenshot https://1.2.3.4
Traceback (most recent call last):
  File "/home/drone/tools/EyeWitness/Python/./EyeWitness.py", line 408, in <module>
    single_mode(cli_parsed)
  File "/home/drone/tools/EyeWitness/Python/./EyeWitness.py", line 229, in single_mode
    result, driver = capture_host(cli_parsed, http_object, driver)
  File "/home/drone/tools/EyeWitness/Python/modules/selenium_module.py", line 210, in capture_host
    opened = urllib.request.urlopen(req, context=context)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.10/http/client.py", line 1259, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object
```

I've got access to this site till the 17th so happy to debug it.

## Expected behavior (vs. what you encountered)
no crash

**Comment by ChrisTruncer** [comment]
Hm, thanks for reporting this. I'll try to re-create it where I can on my side. Based off that error log, it looks like the issue might actually lie within the urllib library, which is odd because I wouldn't expect that. I'll see if I can make trigger the error here.

**Comment by digininja** [comment]
I might be able to get tcpdump running to capture what comes back, but not
sure if that would help as I looked at what is returned when it doesn't
error and it looks normal - I think it is an ESXi box from memory.

**Comment by 0x6d6f7468** [comment]
Yo @ChrisTruncer, I've gotten a couple of folks on our team who've reported the issue to me (I guess I've become BHIS' EW spokesperson? Fair enough).

Just worked through this with Kent and I think we identified where the issue is happening. Seems to be on line [199 of selenium_module.py](https://github.com/FortyNorthSecurity/EyeWitness/blob/2e7b8809552e1fca9e0bb8943f7ff9561df50956/Python/modules/selenium_module.py#L199). Adding a wrapper around the existing try/catch block to manually honor the user agent string CLI argument, then specifying a valid user agent string via the command line, seemed to get around the issue and the errors stopped appearing.

![image](https://user-images.githubusercontent.com/25512187/178069316-c69fe5d6-8dd4-46ec-8c8b-4f62b886edbb.png)

This is far from a permanent fix but I think it narrows down the issue. Might be some flavor of race condition in how that JavaScript is executed. I'll keep looking as time allows and let you know what I find.

Strange thing is, the error is only fatal some of the time. Other times, the error will happen mid-run and EW will keep chugging along happily. Also worth investigation, I suppose.

Thanks!

**Comment by digininja** [comment]
Tell Kent I said hi.

I've not seen it again since but I'll try the fix is I do.

**Comment by ChrisTruncer** [comment]
I just added in the same code into the repo. I'll be curious if this still is happening after this update. Please do let me know if it does.

**Comment by ChrisTruncer** [comment]
And thanks for the help finding it and providing a patch!

**Comment by 0x6d6f7468** [comment]
Not certain I'd call it completely fixed yet, but always happy to help.

I'm still going to try and figure out what's going on with that variable and why it occasionally comes back as `None`.

But, this is a good enough workaround for now so people can get EW to completely run until a more robust solution is found. I'll put in a PR if I figure anything out.
